config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'categories#index'

  resources :categories do
    resources :photos
  end

  resources :privatecats do
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :photos, dependent: :destroy
    has_one_attached :image
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :category
    has_one_attached :image
end

app/models/privatecat.rb
class Privatecat < ApplicationRecord
    has_many_attached :images
    belongs_to :gallery_owner, class_name: "User", foreign_key: 'gallery_owner_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :private_assigns
  has_many :privatecats
  # has_many :private_owner, class_name: "User",
  #                         foreign_key: "administrator_id"

  # belongs_to :administrator, class_name: "User", optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  include Pundit

  # # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas autorisés à accéder à cette gallerie"
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?

  def index
    @categories = policy_scope(Category)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
    authorize @category
  end

  def edit
    @category = Category.find(params[:id])
    authorize @category
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to categories_path
    authorize @category
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
    authorize @category
  end

  private

  def category_params
    params.require(:category).permit(:name, :image)
  end

  def set_category
  @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  after_action :verify_authorized, except: [:index, :show], unless: :skip_pundit?

  def index
    @photos = policy_scope(Photo)
  end

  def show
    @category = Category.find(params[:category_id])
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
    @category = Category.find(params[:category_id])
    authorize @photo
  end

  def create
    @photo = Photo.create(photo_params)
    @photo.category = Category.find(params[:category_id])
    if @photo.save
      redirect_to category_path(@photo.category), notice: 'Photo uploadée.'
    else
      render :new
    end
    authorize @photo
  end

  def edit
    @photo = Photo.find(params[:id])
    @category = @photo.category
    authorize @photo
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to category_path(@photo.category), notice: 'Photo modifiée.'
    else
      render :edit
    end
    authorize @photo
  end

  def destroy
    @category = Category.find(params[:category_id])
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to category_path(@photo.category_id), notice: 'Photo supprimée.'
    authorize @photo
  end

  private

  def photo_params
    params.require(:photo).permit(:name, :description, :image)
  end
end

app/controllers/privatecats_controller.rb
class PrivatecatsController < ApplicationController
  before_action :set_privatecat, only: [:show, :edit, :update, :destroy]
  def index
    @privatecats = policy_scope(Privatecat)
  end

  def show
    @privatecat = Privatecat.find(params[:id])
    @authorized_user = User.find(@privatecat.gallery_owner_id)
    authorize @privatecat
  end

  def new
    @privatecat = Privatecat.new
    @emails = User.all.map { |user| user.email }
    authorize @privatecat
  end

  def create
    @users = User.where(email: params[:privatecat][:gallery_owner])
    @users.each do |user|
      @gallery_owner = user.id
      @privatecat = Privatecat.create(privatecat_params)
      @privatecat.update(gallery_owner_id: @gallery_owner)
    end

    if @privatecat.save
      redirect_to privatecat_path(@privatecat), notice: 'Cat créée.'
    else
      render :new
    end
    authorize @privatecat
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private
  def privatecat_params
    params.require(:privatecat).permit(:name, images: [])
  end

  def set_privatecat
    @privatecat = Privatecat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<div class="banner-home">
  <h1>LAF</h1>
  <h2>Pictures for the Laife</h2>
    <% @categories.each do |category| %>

     <% if category.image.attached? %>
          <%= link_to category_path(category) do %>
          <%= category.name %><br />
              <%= cl_image_tag category.image.key, height: 300, width: 400, crop: :fill %>
          <% end %>
      <% end %>

      <% if policy(category).edit? %>
        <%= link_to edit_category_path(category), class: "text" do %>
          <i class="far fa-edit"></i>
        <% end %>
      <% end %>

      <% if policy(category).destroy? %>
          <%= link_to category, method: :delete, data: { confirm: 'Êtes-vous sûr-e ?' }, class: "text" do %>
          <i class="far fa-trash-alt"></i>
          <% end %>
      <% end %>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1>Categories</h1>
 <p>Créer une nouvelle catégorie</p>
<%= simple_form_for(@category) do |f| %>
  <%= f.input :name%>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

<%= link_to "Retour à l'accueil", root_path %>

app/views/categories/show.html.erb
<h1 class="text-center"><%= @category.name %></h1>
  <div class = "container">
      <div class="cards">
        <% @category.photos.each do |photo|  %>
          <% if photo.image.attached? %>
                    <div class="card-category" style="background-image: url('<%= cl_image_path photo.image.key, garvity: :faces, crop: :fill %>')">
                      <%= photo.name %>
                      <%= photo.description %>
                      <% if policy(photo).destroy? %>
                        <%= link_to category_photo_path(@category, photo), method: :delete, data: { confirm: 'Êtes-vous certain de vouloir effecer cette photo ?' }, class: "text" do %>
                        <i class="far fa-trash-alt"></i>
                        <% end %>
                      <% end %>
                  </div>
          <% end%>
        <% end%>
    </div>
  </div>
<% if policy(@category.photos).create? %>
  <%=link_to 'nouvelle photo', new_category_photo_path(@category)%>
<% end%>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>LAF</h1>
<p>Pictures for the Life</p>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<h1>Photos#new</h1>


<%= simple_form_for [@category,@photo] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
   
    <%= f.input :name, label: "Nom" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :image, as: :file %>

  
    <%= f.button :submit, "Sauvegarder", class: "btn btn-dark" %>  
<% end %>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/photos/update.html.erb
<h1>Photos#update</h1>
<p>Find me in app/views/photos/update.html.erb</p>

app/views/privatecats/create.html.erb
<h1>Privatecats#create</h1>
<p>Find me in app/views/privatecats/create.html.erb</p>

app/views/privatecats/destroy.html.erb
<h1>Privatecats#destroy</h1>
<p>Find me in app/views/privatecats/destroy.html.erb</p>

app/views/privatecats/edit.html.erb
<h1>Privatecats#edit</h1>
<p>Find me in app/views/privatecats/edit.html.erb</p>

app/views/privatecats/index.html.erb
<h1>Privatecats#index</h1>
<p>Find me in app/views/privatecats/index.html.erb</p>
<% @privatecats.each do |privatecat| %>
    <% if policy(privatecat).show? %>
        <%= link_to privatecat_path(privatecat), class: "text" do %>
            <%= privatecat.name%>
            <i class="far fa-edit"></i>
        <% end %>
    <% end %>
<% end %>

app/views/privatecats/new.html.erb
<h1>Privatecats#new</h1>
<p>Find me in app/views/privatecats/new.html.erb</p>
<%= simple_form_for(@privatecat) do |f| %>
     <%= f.input :name%>
     <%= f.input :gallery_owner, as: :select, :label => "Membres", collection: @emails, include_hidden: false%>
     <%= f.input :images, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
<% end %>
<%= link_to "Retour à l'accueil", root_path %>

app/views/privatecats/show.html.erb
<h1><%= @privatecat.name %></h1><br />
<% if current_user.admin? %>
    <h4> Utilisateur autorisé</h4>
    Email: <%= @authorized_user.email %><br />
    Id: <%= @authorized_user.id %><br />
<% end %>
<% @privatecat.images.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

app/views/privatecats/update.html.erb
<h1>Privatecats#update</h1>
<p>Find me in app/views/privatecats/update.html.erb</p>

app/views/shared/_error.html.erb
"Vous n'avez pas de gallerie privée"

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Galeries privées", privatecats_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Créer une catégorie", new_category_path, class: "dropdown-item" %>
            <%# <%= link_to "Editer une catégorie", new_category_path, class: "dropdown-item" %>
            <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>